apiVersion: v1
kind: Service
metadata:
  name: client-clusterip
spec:
  selector:
    app: client-app
  ports:
    - port: 80
      name: intent-port
      targetPort: main-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-limited
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      containers:
        - image: blog-client
          ports:
            - containerPort: 80
              name: main-port

          name: cient-container
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
