apiVersion: v1
kind: Service
metadata:
  name: comments-clusterip
spec:
  selector:
    app: comments-app
  ports:
    - port: 4001
      name: intent-port
      targetPort: main-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment-limited
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments-app
  template:
    metadata:
      labels:
        app: comments-app
    spec:
      containers:
        - image: blog-comments
          name: comments-container
          ports:
            - containerPort: 4001
              name: main-port
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
