apiVersion: v1
kind: Service
metadata:
  name: event-bus-clusterip
spec:
  selector:
    app: event-bus-app
  ports:
    - port: 4005
      name: intent-port
      targetPort: main-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-deployment-limited
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus-app
  template:
    metadata:
      labels:
        app: event-bus-app
    spec:
      containers:
        - image: blog-event-bus
          name: event-bus-container
          ports:
            - containerPort: 4005
              name: main-port
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
