apiVersion: v1
kind: Service
metadata:
  name: moderation-clusterip
spec:
  selector:
    app: moderation-app
  ports:
    - port: 4003
      name: intent-port
      targetPort: main-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-deployment-limited
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moderation-app
  template:
    metadata:
      labels:
        app: moderation-app
    spec:
      containers:
        - image: blog-moderation
          name: moderation-container
          ports:
            - containerPort: 4003
              name: main-port
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
