apiVersion: v1
kind: Pod
metadata:
  name: event-bus-pod-limited
  labels:
    app: event-bus-app
spec:
  containers:
    - name: event-bus-container
      image: blog-event-bus
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4005
      resources:
        limits:
          memory: "128Mi" #128 MB
          cpu: "100m" #200 millicpu (.2 cpu or 20% of the cpu)
