apiVersion: v1
kind: Pod
metadata:
  name: moderation-pod-limited
  labels:
    app: moderation-app
spec:
  containers:
    - name: moderation-container
      image: moderation
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4003
      resources:
        limits:
          memory: "128Mi" #128 MB
          cpu: "100m" #200 millicpu (.2 cpu or 20% of the cpu)
