apiVersion: v1
kind: Pod
metadata:
  name: posts-pod-limited
  labels:
    app: posts-app
spec:
  containers:
    - name: posts-container
      image: blog-posts
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4000
      resources:
        limits:
          memory: "128Mi" #128 MB
          cpu: "100m" #200 millicpu (.2 cpu or 20% of the cpu)
