apiVersion: v1
kind: Pod
metadata:
  name: query-pod-limited
  labels:
    app: query-app
spec:
  containers:
    - name: posts-container
      image: blog-query
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 4002
      resources:
        limits:
          memory: "128Mi" #128 MB
          cpu: "100m" #200 millicpu (.2 cpu or 20% of the cpu)
